sudo: false

language: java

script: mvn clean install -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

after_success:
    - chmod 777 scripts/check.sh
    - scripts/check.sh