sudo: false

language: java

script: 
    - mvn clean install -Dmaven.javadoc.skip=true
    - chmod 777 scripts/*.sh
    - export EMAIL=`./scripts/set_email.sh`
    - scripts/check.sh

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: always
    on_failure: always

