sudo: false

language: java

script: 
    - mvn clean install -Dmaven.javadoc.skip=true
    - chmod 777 travis-scripts/*.sh
    - travis-scripts/check-pom.sh

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always
