sudo: false

language: java

env:
    - EMAIL=./scripts/set_email.sh

script: 
    - mvn clean install -Dmaven.javadoc.skip=true
    - chmod 777 scripts/check.sh
    - scripts/check.sh

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - $EMAIL
      - ghurley@murex.com
    on_success: always
    on_failure: always

